AWSTemplateFormatVersion: "2010-09-09"
Description: CFn Artifacts Bucket

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub bookmarks-artifacts-${AWS::AccountId}-${AWS::Region}
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 7
            Status: Enabled

Outputs:
  ArtifactBucketName:
    Value: !Ref ArtifactBucket